#设置端口
server:
  port: 80
  servlet:
    context-path: /cbserver

#设置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cb?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # mongodb配置
  data:
    mongodb:
      uri: mongodb://yjy:yjy@localhost:27017/strategy

#mybatis配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.yjy.cbcollection_server.pojo
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: debug
